name: 01-Building-Blocks
on: [push, workflow_dispatch]

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "hello world"
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Non failing step
              run: |
                echo "I will pass"
                exit 0
            - name: Say goodbye
              run: echo "goodbye"
                