name: 05-1-Filters-Activity
on:  
    pull_request:
        types: [opened,synchronize]
        branches:
            - main

jobs:
    one-job:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Job
              run: echo "Running whenever a PR is opened or synchronized AND base branch is main"