name: 12-Outputs
on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
            output1: ${{ steps.build.outputs.output1 }}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo $GITHUB_OUTPUT
            - name: Build
              id: build
              run: |
                echo "status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"
                echo "output1=value1" >> "$GITHUB_OUTPUT"
                echo "output2=value2" >> "$GITHUB_OUTPUT"
            - name: Print GITHUB_OUTPUT path
              run: |
                echo $GITHUB_OUTPUT
                echo "mistake=true" > "$GITHUB_OUTPUT"
                echo $GITHUB_OUTPUT
    deploy:
        runs-on: ubuntu-latest
        needs:
            - build
        if: ${{ needs.build.outputs.build-status == 'success' }}
        steps:
            - name: Deploy
              run: echo "Deploying ... "   
            - name: Print outputs
              run: echo ${{ needs.build.outputs.output1 }}           
