name: 15-Matrices
on:
    - workflow_dispatch

jobs:
    backwards-compatibility:
        runs-on: ubuntu-latest
        name: ${{matrix.os}}-${{matrix.node-versions}}
        strategy:
            matrix:
                node-versions: [ 18.x, 20.x, 21.x ]
                os:
                    - ubuntu-latest
                    - windows-latest
        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-versions}}
            - name: Perform some tests
              run: echo "Running tests on OS - ${{matrix.os}} and NodeJS version ${{matrix.node-versions}}"
            
            
