name: 18.2 - reusable-workflows
on:
    workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/18-1-reusable-workflows-definition.yaml
        with:
            target-directory: my_dir
    print-outputs:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Print outputs
              run: |
                echo "Build status: ${{ needs.deploy.outputs.build-status }}"
                echo "URL: ${{ needs.deploy.outputs.url }}"